version: "3.9"
services:
  react:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/code
    working_dir: /code
    command: "npm start"
  express:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/code
    working_dir: /code
    command: "npx ts-node src/server/app.ts"
